---
output:
  word_document:
    reference_docx: report_HR_style_template.docx
always_allow_html: true
---

```{r setup, include=FALSE}
path_root <-
  "C:/Users/kibi/OneDrive - Danmarks Tekniske Universitet/stock_coord_work/spr.27.3a4/2026_spr.27.3a4_RDBES_combined/report_scripts/"

# path_root <-
#   "Q:/mynd/kibi/SC_work/her.27.20-24/2024_her.27.20-24_RDBES_combined/"

knitr::opts_knit$set(root.dir = path_root)

knitr::opts_chunk$set(echo = F,
                      warning = F,
                      message = F)

library(dplyr)
library(flextable)
library(tidyverse)
library(readxl)

options(scipen = 9999)

year_last <- 2025
```

```{r t_8, ft.align="left"}
# Input ----
dat <-
  read.csv(paste0(paste0("../data/11_catch_year_country_div_2005_", year_last, ".csv")), sep = ";")

total <- subset(dat, area == "Total")
total$catch_1000t[total$catch_1000t <= 0.049 & total$catch_1000t != 0] <- "+"
total_t <- arrange(tidyr::spread(total, key = ctry, value = catch_1000t, fill = 0), year, area)
total_t <- select(total_t, year, area, BE, DE, DK, FO, FR, `GB-EAW`, `GB-SCT`, NL, NO, SE, Total)
names(total_t)
names(total_t) <- c("Year", "Area", "Belgium", "Germany", "Denmark", 
                    "Faroe Islands", "France", "England and Wales", 
                    "Scotland", "Netherlands", "Norway", "Sweden", "Total")

total_t$Belgium[total_t$Year == year_last + 1] <- "-"
total_t$Germany[total_t$Year == year_last + 1] <- "-"
total_t$`Faroe Islands`[total_t$Year == year_last + 1] <- "-"
total_t$France[total_t$Year == year_last + 1] <- "-"
total_t$`England and Wales`[total_t$Year == year_last + 1] <- "-"
total_t$Scotland[total_t$Year == year_last + 1] <- "-"
total_t$Netherlands[total_t$Year == year_last + 1] <- "-"
total_t$Norway[total_t$Year == year_last + 1] <- "-"
total_t$Sweden[total_t$Year == year_last + 1] <- "-"


# dat_1_t$Denmark[dat_1_t$Denmark == 0] <- NA
# dat_1_t$`Faroe Islands`[dat_1_t$`Faroe Islands` == 0] <- NA
# dat_1_t$Finland[dat_1_t$Finland == 0] <- NA
# dat_1_t$Germany[dat_1_t$Germany == 0] <- NA
# dat_1_t$Lithuania[dat_1_t$Lithuania == 0] <- NA
# # dat_1_t$Netherlands[dat_1_t$Netherlands == 0] <- NA
# dat_1_t$Norway[dat_1_t$Norway == 0] <- NA
# dat_1_t$Poland[dat_1_t$Poland == 0] <- NA
# dat_1_t$Sweden[dat_1_t$Sweden == 0] <- NA
# dat_1_t$Total[dat_1_t$Total == 0] <- NA

total_t$Year <- as.character(total_t$Year)
total_t <- select(total_t, -Area)

# Flextable ----

set_flextable_defaults(
  font.family = "Calibri",
  font.size = 7,
  padding.bottom = 0,
  padding.top = 0
)

t1 <- flextable(total_t) %>%
  set_table_properties(width = 1, layout = "autofit") %>%
  bold(part = "header") %>%
  padding(padding.bottom = 0, part = "all") %>%
  padding(padding.top = 0, part = "all") %>%
  bg(bg = "#B7D1C3", part = "header") %>%
  border_inner_h(part = "all") %>%
  footnote(
    i = total_t$Year == year_last,
    j = 1,
    value = as_paragraph(c("Preliminary")),
    ref_symbols = "*"
  ) %>% merge_v(part = "footer")  %>%
  footnote(
    i = total_t$Year == year_last + 1,
    j = 1,
    value = as_paragraph(c(
      "Preliminary catches reported from Denmark up until 01 March."
    )),
    ref_symbols = "**"
  ) %>%
  colformat_num(big.mark = "", na_str = "-")

t1
```
